// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxOp6Z4frs_OUCn44hlEFAUUjCVXt_DaU',
    appId: '1:595794346344:web:b1c61909afc26043a916dd',
    messagingSenderId: '595794346344',
    projectId: 'inpark-5a693',
    authDomain: 'inpark-5a693.firebaseapp.com',
    storageBucket: 'inpark-5a693.appspot.com',
    measurementId: 'G-SQPPDZCJ2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAesx0GANv4-I5x2LtQy6MwJrHos3CjKgE',
    appId: '1:595794346344:android:e3cfec12e84ed3a3a916dd',
    messagingSenderId: '595794346344',
    projectId: 'inpark-5a693',
    storageBucket: 'inpark-5a693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPduVCB9zGe9-ARpzsJ6TAugorPAbhbU',
    appId: '1:595794346344:ios:2515dd7204aa5548a916dd',
    messagingSenderId: '595794346344',
    projectId: 'inpark-5a693',
    storageBucket: 'inpark-5a693.appspot.com',
    iosClientId: '595794346344-bqa5c5cclm6nrqg7a0p2317bsd7n7o94.apps.googleusercontent.com',
    iosBundleId: 'com.example.inpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPduVCB9zGe9-ARpzsJ6TAugorPAbhbU',
    appId: '1:595794346344:ios:2515dd7204aa5548a916dd',
    messagingSenderId: '595794346344',
    projectId: 'inpark-5a693',
    storageBucket: 'inpark-5a693.appspot.com',
    iosClientId: '595794346344-bqa5c5cclm6nrqg7a0p2317bsd7n7o94.apps.googleusercontent.com',
    iosBundleId: 'com.example.inpark',
  );
}
